openapi: 3.0.1
info:
  title: TodoListApi
  version: '1.0'
paths:
  "/api/Tasks":
    get:
      tags:
      - Tasks
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Task"
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Task"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Task"
    post:
      tags:
      - Tasks
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Task"
          text/json:
            schema:
              "$ref": "#/components/schemas/Task"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/Task"
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                "$ref": "#/components/schemas/Task"
            application/json:
              schema:
                "$ref": "#/components/schemas/Task"
            text/json:
              schema:
                "$ref": "#/components/schemas/Task"
  "/api/Tasks/{id}":
    get:
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                "$ref": "#/components/schemas/Task"
            application/json:
              schema:
                "$ref": "#/components/schemas/Task"
            text/json:
              schema:
                "$ref": "#/components/schemas/Task"
    delete:
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
      additionalProperties: false
